name: NodeJS 

on:
    # Trigger the workflow on push,
    # but only for the pre-production branch
    push:
        branches:
            - main
env:
    AWS_REPOSITORY_URL: ${{ secrets.AWS_REPOSITORY_URL }}
    GITHUB_TOKEN: ${{ secrets.AWS_GITHUB_TOKEN }}

jobs:
    NodeJs:
        runs-on: ubuntu-latest

        steps:
             - name: configure The IAM cred
               uses: aws-actions/configure-aws-credentials@v1
               with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_id }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: ap-south-1

             - name: Login in to Amazon ECR
               id: login-ecr
               uses: aws-actions/amazon-ecr-login@v1  
             
             - uses: actions/checkout@v2
             - name: Build the Docker image
               run: |
                  docker build -t 758671678745.dkr.ecr.ap-south-1.amazonaws.com/demo-project:$GITHUB_REF_NAME-$GITHUB_SHA . 
                  docker push 758671678745.dkr.ecr.ap-south-1.amazonaws.com/demo-project:$GITHUB_REF_NAME-$GITHUB_SHA
                  